### ISSUE TITLE
0.3.3 release onwards have broken Gurobi solves for large models.

### ISSUE THREAD

**Issue by yuchen-w** [PyPSA/linopy#329] opened 2024-07-18 13:39 UTC
Issue originally reported in #192 and fixed in 0.3.1 has resurfaced.
My large model solves fine in 0.3.1 and 0.3.2 but not in 0.3.3 or the latest version. I've confirmed with the minimal example in #192

**Comment by FabianHofmann** [comment] 2024-07-18 13:43
@yuchen-w sorry to hear that, I assume that also counts for the latest version? Could you figure out which changes let the error resurface?

**Comment by yuchen-w** [comment] 2024-07-18 13:54
Yes indeed. Sorry I can't help you there, I'm not familiar with the code base.
I know my model runs with the same error as #192 and I've been able to reproduce the example in #192 in versions after 0.3.2

**Comment by aurelije** [comment] 2024-07-19 07:37
I am wondering what is the usefulness of Gurobi model that goes into result: https://github.com/PyPSA/linopy/blob/f252fdef4b7e3d0a47e8cd8eedb5c143f396328a/linopy/solvers.py#L728C12-L728C39

Maybe I do not know Gurobi well, but to me it looks they have made model class completely useless without environment and in that lane where Result is made, we have environment closed. So it only makes easier to create bug by trying to use useless gurobi model object.

**Comment by dannyopts** [comment] 2024-07-21 20:20
Looks like the issue is simply that this line and the line below got unindented again. 

https://github.com/PyPSA/linopy/blob/f252fdef4b7e3d0a47e8cd8eedb5c143f396328a/linopy/solvers.py#L725

The fix is simply to reindent it like in this PR https://github.com/PyPSA/linopy/pull/193/files

I'm a little confused by the git blame though, since the other changes in that PR seem to be there, but the last change to that line was supposedly 2 years ago?

@aurelije I use with gurobipy.Env() outside of linopy and pass in the env, so it is useful to be able to access this after linopy has completed.

Seeing as this has recurred, and is due to an async race condition that often wont show up in test cases, maybe it makes sense to find a way to test for this bug or make a production code change which means that we assert the model or env is open when it is queried? It feels like if there isnt something like a test preventing it this will keep happening. 

Looking at the gurobi docs there isnt an is_closed method, so I dont know how to check that reliably and the best that I can come up with as a test is having a fixture which mocks the model creation but when I sketched that out it really didnt seem like the right solution.

**Comment by aurelije** [comment] 2024-07-22 08:47
@dannyopts yes, Gurobi API is not the best for end users... But as it states here: https://docs.gurobi.com/projects/optimizer/en/current/reference/python/env.html#Env.close it really means that gurobi model should not be used after it's Env is closed and I do not know for way to disassociate model and environment after end of optimization. The only way is not to close Env meaning (as you are doing) that Env is created manually and supplied to this method so it doesn't get created inside. But that case should be special, in normal use case you should not create Env on your own, and exactly that case is problematic

**Closed** 2024-07-23 07:49 UTC
